---
title: "Quiz 2"
author: "Dustin Lanning"
date: "July 9, 2019"
output: 
  html_document: 
    keep_md: yes
---

##Load the Data

```{r}
suppressMessages(library(ggplot2))
suppressMessages(library(quanteda))
suppressMessages(library(ngram))

blogs_data<-readLines("final/en_US/en_US.blogs.txt", encoding = "UTF-8", skipNul = TRUE)
news_data<-readLines("final/en_US/en_US.news.txt", encoding = "UTF-8", skipNul = TRUE, warn = FALSE)
twitter_data<-readLines("final/en_US/en_US.twitter.txt", encoding = "UTF-8", skipNul = TRUE)
```

##Clean the Data

```{r}
cleanBlogs<-preprocess(blogs_data,
                   case = "lower",
                   remove.numbers = TRUE,
                   remove.punct = TRUE,
                   fix.spacing = TRUE)

cleanNews<-preprocess(news_data, 
                     case = "lower",
                     remove.numbers = TRUE,
                     remove.punct = TRUE,
                     fix.spacing = TRUE)

cleanTwitter<-preprocess(twitter_data,
                         case = "lower",
                         remove.numbers = TRUE,
                         remove.punct = TRUE,
                         fix.spacing = TRUE)
```

##Trigram

```{r}
cleanData<-concatenate(cleanBlogs, cleanNews, cleanTwitter)
trigram<-ngram(cleanData, n = 3)
df<-get.phrasetable(trigram)
head(df)
#trigramSort<-topfeatures(trigramMat, 15)
#trigramDF<-data.frame(words = names(trigramSort), freq = trigramSort)
```

##1. The guy in front of me just bought a pound of bacon, a bouquet, and a case of

```{r}
#dfm_select(trigramMat, pattern = phrase("^case of"), selection = "keep", valuetype = "glob")
```